name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Mago
        run: vendor/bin/mago format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run Mago
          branch: ${{ github.head_ref }}
